# Generated by Django 4.2.1 on 2023-05-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='website.realestatedeveloper')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('apartment_lot_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('real_estate_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.realestateprogram')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.userprofile')),
            ],
        ),
    ]
