# Generated by Django 4.2.1 on 2023-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
