# Generated by Django 4.2.1 on 2023-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_city_department_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='department_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
