# Generated by Django 4.2.1 on 2023-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_city_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
