# Generated by Django 4.2.1 on 2023-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_city_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='city',
            name='department_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
