# Generated by Django 4.2.1 on 2023-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=23, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=23, max_digits=30, null=True),
        ),
    ]
