# Generated by Django 4.2.1 on 2023-06-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
    ]
