# Generated by Django 4.2.1 on 2023-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_realestatedeveloper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateprogram',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
