# Generated by Django 4.2.1 on 2023-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_article_imagearticle_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
