# Generated by Django 4.2.1 on 2023-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_section_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='associated_articles',
            field=models.ManyToManyField(blank=True, to='website.article'),
        ),
    ]
