# Generated by Django 4.2.1 on 2023-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImageArticle',
        ),
    ]
