# Generated by Django 4.2.1 on 2023-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_section_alt_text_section_caption_delete_imagearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image_position',
            field=models.CharField(blank=True, choices=[('title', 'Image de titre'), ('left', 'Image à gauche'), ('right', 'Image à droite')], default='left', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
