# Generated by Django 4.2.1 on 2023-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_realestateprogram_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
