# Generated by Django 4.2.1 on 2023-11-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_city_region_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.city'),
        ),
    ]
