# Generated by Django 4.2.1 on 2023-11-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.state'),
        ),
    ]
