# Generated by Django 4.2.1 on 2023-12-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_state_city_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.state'),
            preserve_default=False,
        ),
    ]
