# Generated by Django 4.2.1 on 2023-12-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_address_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='realestateprogram',
            name='unique_program',
        ),
    ]
