# Generated by Django 4.2.1 on 2023-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_userprofile_ggender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ggender',
            new_name='gender',
        ),
    ]
