# Generated by Django 4.2.1 on 2023-08-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_unvalidatedrealestateprogram'),
        ('forum', '0005_rename_ggender_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtheme',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='real_estate_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.realestateprogram'),
        ),
    ]
