# Generated by Django 4.2.1 on 2023-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forumtheme_order_alter_forumpost_real_estate_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtheme',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
