# Generated by Django 4.2.1 on 2023-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_forumtheme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtheme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
