# Generated by Django 4.2.1 on 2023-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_forumtheme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
