# Generated by Django 4.2.1 on 2023-08-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_forumpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='attachment',
        ),
    ]
