# Generated by Django 4.2.1 on 2023-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_forumtheme_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtheme',
            name='icon',
        ),
        migrations.AddField(
            model_name='forumtheme',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
