# Generated by Django 4.2.1 on 2023-09-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_forumtheme_icon_forumtheme_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
