# Generated by Django 4.2.1 on 2023-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_reply_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtheme',
            name='color',
            field=models.CharField(default='0, 0, 255', max_length=11),
        ),
    ]
